In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gzip

In [2]:
ls /Users/natasharecoder/Documents/NYU

ID.png         MichelmannLab/ Term1/         Term2/         Term3/

In [3]:
pwd

'/Users/natasharecoder/Documents/NYU/Term3/Capstone/Capstone'

In [5]:
# Path to GWAS file
#gwas_file_path = '/Users/natasharecoder/Library/CloudStorage/GoogleDrive-npr264@nyu.edu/Other computers/My Mac/NYU/Term3/Capstone/Data/50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz'
gwas_file_path = '../Data/50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz'

# Open and read the compressed .bgz file using gzip
with gzip.open(gwas_file_path, 'rt') as f:
    # Load the file into a pandas DataFrame
    gwas_df = pd.read_csv(f, sep='\t')

In [22]:
# Path to GWAS file
#gwas_file_path = '/Users/natasharecoder/Library/CloudStorage/GoogleDrive-npr264@nyu.edu/Other computers/My Mac/NYU/Term3/Capstone/Data/50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz'
gwas_file_path = '../Data/50_irnt.ldsc.imputed_v3.both_sexes.tsv.bgz'

# Open and read the compressed .bgz file using gzip
with gzip.open(gwas_file_path, 'rt') as f:
    # Load the file into a pandas DataFrame
    gwas_df = pd.read_csv(f, sep='\t')

In [23]:
gwas_df

                SNP A1 A2       N         Z
0         rs1000000  A  G  360388 -0.541180
1        rs10000010  C  T  360388  2.340400
2         rs1000002  T  C  360388  1.342000
3        rs10000023  T  G  360388 -0.056916
4         rs1000003  G  A  360388 -1.743300
...             ... .. ..     ...       ...
1096643   rs9999963  C  T  360388 -1.298600
1096644   rs9999966  T  C  360388 -0.377410
1096645   rs9999978  C  T  360388  0.157130
1096646   rs9999979  T  C  360388  0.593340
1096647   rs9999995  G  A  360388  1.545600

[1096648 rows x 5 columns]

In [27]:
# New column order
new_order = ['SNP', 'A1', 'A2', "Z","N"]

# Reorder the DataFrame columns
gwas_df = gwas_df[new_order]

In [28]:
gwas_df.to_csv('GWAS_SumStats.txt', sep = " ", index = False)

In [7]:
gwas_df = gwas_df[gwas_df['pval']>= 0]

In [8]:
gwas_df = gwas_df[~gwas_df['pval'].isna()]

In [9]:
gwas_df

,variant,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,pval
0,1:15791:C:T,T,5.440760e-09,True,360388,0.003922,0.003474,18.049900,178.468000,0.101138,0.919441
1,1:69487:G:A,A,5.761760e-06,True,360388,4.152940,-0.087536,-0.041345,0.349577,-0.118272,0.905852
2,1:69569:T:C,C,1.881580e-04,True,360388,135.620000,-2.079970,-0.046994,0.062695,-0.749571,0.453514
3,1:139853:C:T,T,5.674710e-06,True,360388,4.090200,-0.105659,-0.042056,0.349588,-0.120302,0.904244
4,1:692794:CA:C,C,1.106010e-01,False,360388,79718.500000,101.503000,0.000797,0.002899,0.274788,0.783479
...,...,...,...,...,...,...,...,...,...,...,...
13791462,X:154929412:C:T,T,2.454380e-01,False,360388,176906.000000,-787.373000,-0.001657,0.001588,-1.044020,0.296477
13791463,X:154929637:CT:C,C,2.297000e-01,False,360388,165562.000000,-734.113000,-0.001654,0.001657,-0.998454,0.318060
13791464,X:154929952:CAA:C,C,2.393990e-01,False,360388,172553.000000,-480.000000,-0.001689,0.001670,-1.011490,0.311783
13791465,X:154930230:A:G,G,2.458510e-01,False,360388,177204.000000,-706.111000,-0.001520,0.001587,-0.957369,0.338381
13791466,X:154930487:T:A,A,1.955520e-02,False,360388,14094.900000,-265.942000,-0.013297,0.005446,-2.441660,0.014620

In [10]:
#ref = '/Users/natasharecoder/Library/CloudStorage/GoogleDrive-npr264@nyu.edu/Other computers/My Mac/NYU/Term3/Capstone/Capstone/maf01.kgp.snps'
ref = 'maf01.kgp.snps'

with open(ref, "r") as f:
    ref_df = pd.read_csv(f, sep='\t')

In [11]:
ref_df = ref_df.rename(columns={"SNP": "variant"})

In [12]:
ref_df

                  variant         rsid
0         10:10000018:A:G    rs6602381
1        10:100000625:A:G    rs7899632
2        10:100000645:A:C   rs61875309
3        10:100001867:C:T  rs150203744
4        10:100002464:T:C  rs111551711
...                   ...          ...
8136095    9:99997707:C:T   rs11794422
8136096    9:99998403:C:T   rs10981296
8136097    9:99998646:C:G   rs10981297
8136098     9:9999880:G:C  rs151001359
8136099    9:99999468:A:G   rs10981301

[8136100 rows x 2 columns]

In [14]:
#Goal: rs id, allele1, allele2, freq allele 1, p, N

In [15]:
#never less than 0.5, you need to do 1 minus to get the

In [13]:
gwas_df.sort_values('minor_AF', ascending = False)

,variant,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,pval
2011798,2:210268142:G:A,G,5.000000e-01,False,360388,360388.000000,775.938000,0.003274,0.001651,1.982940,0.047375
6831735,8:23739375:G:A,G,5.000000e-01,False,360388,360388.000000,724.666000,0.004359,0.001651,2.639840,0.008295
7878702,9:120620457:T:C,C,5.000000e-01,False,360388,360388.000000,231.576000,0.005245,0.001652,3.175140,0.001498
2011679,2:210251735:C:T,T,5.000000e-01,False,360388,360388.000000,791.978000,0.003255,0.001651,1.972020,0.048608
2275578,3:16188183:A:AT,A,5.000000e-01,False,360388,360388.000000,-1675.540000,-0.002843,0.001654,-1.719500,0.085524
...,...,...,...,...,...,...,...,...,...,...,...
5174804,6:32362802:C:A,A,5.440760e-09,True,360388,0.003922,0.002564,281.417000,178.465000,1.576870,0.114826
12116007,18:21121296:A:G,G,5.440760e-09,True,360388,0.003922,0.007538,280.655000,178.469000,1.572570,0.115820
6986305,8:59484770:A:G,G,5.440760e-09,True,360388,0.003922,0.003845,25.356600,178.468000,0.142080,0.887017
6986374,8:59499038:A:G,G,5.440760e-09,True,360388,0.003922,0.000452,-127.012000,178.470000,-0.711670,0.476669
0,1:15791:C:T,T,5.440760e-09,True,360388,0.003922,0.003474,18.049900,178.468000,0.101138,0.919441

In [14]:
def repeated_forward_merge(gwas_df, gtf_df):
    # Initial sorting of key columns for the first merge
    gwas_sorted = gwas_df[['variant', 'minor_allele', 'minor_AF', 'n_complete_samples', 'pval']].sort_values('variant')
    ref_sorted = ref_df.sort_values('SNP')

#     # Ensure both 'start' columns are of the same type (convert to float to handle NaNs)
#     gtf_sorted['start'] = gtf_sorted['start'].astype(float)
#     gwas_sorted['pos'] = gwas_sorted['pos'].astype(float)

    # First merge_asof
    gwas_sorted.merge(
        ref_sorted, 
        how='inner', 
        on='variant')

In [15]:
gwas_sorted = gwas_df[['variant', 'minor_allele', 'minor_AF', 'n_complete_samples', 'pval']].sort_values('variant')
ref_sorted = ref_df.sort_values('variant')

In [20]:
#     # Ensure both 'start' columns are of the same type (convert to float to handle NaNs)
#     gtf_sorted['start'] = gtf_sorted['start'].astype(float)
#     gwas_sorted['pos'] = gwas_sorted['pos'].astype(float)

merged_df = gwas_sorted.merge(
    ref_sorted, 
    how='inner', 
    on='variant')

In [21]:
merged_df

,variant,minor_allele,minor_AF,n_complete_samples,pval,rsid
0,10:10000018:A:G,G,0.447816,360388,9.998500e-02,rs6602381
1,10:100000625:A:G,G,0.432818,360388,2.070100e-13,rs7899632
2,10:100000645:A:C,C,0.205457,360388,2.303060e-06,rs61875309
3,10:100001867:C:T,T,0.014127,360388,3.586790e-01,rs150203744
4,10:100002464:T:C,C,0.013226,360388,5.283790e-01,rs111551711
...,...,...,...,...,...,...
8136095,9:99997707:C:T,T,0.453375,360388,9.786090e-03,rs11794422
8136096,9:99998403:C:T,T,0.450696,360388,7.826870e-03,rs10981296
8136097,9:99998646:C:G,G,0.189912,360388,8.364440e-01,rs10981297
8136098,9:9999880:G:C,C,0.013238,360388,1.359970e-01,rs151001359
8136099,9:99999468:A:G,G,0.094658,360388,4.113530e-01,rs10981301

In [20]:
merged_df.columns

Index(['variant', 'minor_allele', 'minor_AF', 'n_complete_samples', 'pval',
       'rsid'],
      dtype='object')

In [19]:
1 + 1

2

In [17]:
merged_df['allele1'] = merged_df['variant'].str[-3]

In [18]:
merged_df['major_AF'] = 1 - merged_df['minor_AF']

In [32]:
merged_df = merged_df.rename(columns={"major_AF": "Freq.Allele1.HapMapCEU", "pval": "p", "n_complete_samples": "N", "minor_allele": "Allele2", 'allele1': 'Allele1', 'rsid': 'MarkerName'})

In [33]:
merged_df = merged_df.drop(columns = ['variant'])

In [34]:
c

In [35]:
pwd

'/Users/natasharecoder/Documents/NYU/Term3/Capstone/Capstone'

In [36]:
merged_df.to_csv('Pre_SumStats.txt', sep = " ", index = False)


the giant data has allele1 as the major allele becuase it says Freq.Allele1.HapMapCEU and then the vals are all >0.5
So we made minor allele labeled allele 2